FROM debian:11

ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash
ENV TZ America/Sao_Paulo
ENV ROOT_PASS=password

## Criando a imagem docker
## docker build --no-cache -t debian-ssh .


RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN sed -i 's|# export LS_OPTIONS|export LS_OPTIONS|' /root/.bashrc; sed -i 's|# alias|alias|' /root/.bashrc; source /root/.bashrc

RUN apt-get update -qq \
    && apt-get install -yqq --no-install-recommends ncurses-base xz-utils procps net-tools \
    openssh-server openssh-client sudo hostname wget curl python3 ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archive/*.deb

RUN ssh-keygen -A \
    && mkdir -p /var/run/sshd \
    && sed -i -r 's/.?UseDNS\syes/UseDNS no/' /etc/ssh/sshd_config \
    && sed -i -r 's/.?ChallengeResponseAuthentication.+/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config \
    && sed -i -r 's/.?PermitRootLogin.+/PermitRootLogin yes/' /etc/ssh/sshd_config

## https://github.com/ochinchina/supervisord
COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord

RUN curl -skLO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz \
    && tar -xf upx-*.tar.xz; mv upx-*/upx /usr/local/bin/; rm -rf upx-3.* \
    && upx --best --lzma /usr/local/bin/supervisord
    
RUN curl -skLO https://github.com/girigiribauer/go-pwgen/releases/download/v0.2.1/pw-linux-amd64.tar.gz \
    && tar -xf pw-linux-amd64.tar.gz; mv pw /usr/local/bin/pwgen; rm -f pw-linux-amd64.tar.gz \
    && upx --best --lzma /usr/local/bin/pwgen    


EXPOSE 9001 22

COPY container-files /
ENTRYPOINT ["/config/bootstrap.sh"]
