FROM opensuse/leap:15

## https://github.com/YuzhongHuangCS/opensuse-ssh

ENV TZ America/Sao_Paulo
ENV ROOT_PASS=password

## Criando a imagem docker
## docker build --no-cache -t opensuse-ssh .

RUN echo "alias ls='ls --color=auto'" >> /root/.bashrc

RUN zypper ref -s \
    && zypper -n in --no-recommends tar xz gzip net-tools wget curl python39 ca-certificates \
    openssh-server openssh-clients sudo hostname net-tools-deprecated iproute2 \
    && zypper clean -a

RUN ssh-keygen -A \
    && sed -i -r 's/.?UseDNS\syes/UseDNS no/' /etc/ssh/sshd_config \
    && sed -i -r 's/.?ChallengeResponseAuthentication.+/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config \
    && sed -i -r 's/.?PermitRootLogin.+/PermitRootLogin yes/' /etc/ssh/sshd_config

## https://github.com/ochinchina/supervisord
COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord

RUN curl -skLO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz \
    && tar -xf upx-*.tar.xz; mv upx-*/upx /usr/local/bin/; rm -rf upx-3.* \
    && upx --best --lzma /usr/local/bin/supervisord
    
RUN curl -skLO https://github.com/girigiribauer/go-pwgen/releases/download/v0.2.1/pw-linux-amd64.tar.gz \
    && tar -xf pw-linux-amd64.tar.gz; mv pw /usr/local/bin/pwgen; rm -f pw-linux-amd64.tar.gz \
    && upx --best --lzma /usr/local/bin/pwgen    


EXPOSE 9001 22

COPY container-files /
VOLUME ["/data"]
ENTRYPOINT ["/config/bootstrap.sh"]
