FROM alpine:latest

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

ENV TZ America/Sao_Paulo
ENV ROOT_PASS=password

#Install
RUN apk update \
	&& apk add --no-cache --upgrade busybox-extras sudo iputils ncurses curl wget xz tzdata \
	&& apk add --no-cache --upgrade ca-certificates bash openssh-server openssh-client python3 \
	&& rm -rf /var/lib/{cache,log}/ \
	&& rm -rf /var/lib/apt/lists/*.lz4; rm -rf /var/log/*; rm -rf /tmp/* /var/tmp/* \	
	&& rm -rf /usr/share/doc/; rm -rf /usr/share/man/; rm -rf /var/cache/apk/*

RUN ssh-keygen -A \
    && sed -i -r 's/.?UseDNS\syes/UseDNS no/' /etc/ssh/sshd_config \
    && sed -i -r 's/.?ChallengeResponseAuthentication.+/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config \
    && sed -i -r 's/.?PermitRootLogin.+/PermitRootLogin yes/' /etc/ssh/sshd_config

## https://github.com/ochinchina/supervisord
COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord

RUN curl -skLO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz \
    && tar -xf upx-*.tar.xz; mv upx-*/upx /usr/local/bin/; rm -rf upx-3.* \
    && upx --best --lzma /usr/local/bin/supervisord
    
RUN curl -skLO https://github.com/girigiribauer/go-pwgen/releases/download/v0.2.1/pw-linux-amd64.tar.gz \
    && tar -xf pw-linux-amd64.tar.gz; mv pw /usr/local/bin/pwgen; rm -f pw-linux-amd64.tar.gz \
    && upx --best --lzma /usr/local/bin/pwgen
    
  
EXPOSE 9001 22

COPY container-files /
VOLUME ["/data"]
ENTRYPOINT ["/config/bootstrap.sh"]
